const BUILD='V4 · build 01';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const uid=(p='id')=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

let photos=[], phrases=[], stickers=[], projects=[], objectUrls=[], heroIndex=0, toastTimer;
const state={kind:'story',format:'story',activeSlide:0,slides:[],selectedLayerId:null,projectId:null,title:'Nuovo progetto',activeTool:'media',phraseFilter:'all',stickerFilter:'Tutti'};

const templateDefs=[
 {id:'m1',cat:'morning',title:'Buongiorno essenziale',subtitle:'testo + sfondo avorio',preview:2,photo:false,text:'Buongiorno. Un giorno alla volta.',bg:'cream',font:'script',look:'warm'},
 {id:'m2',cat:'morning',title:'Buongiorno fotografico',subtitle:'foto sostituibile',preview:3,photo:true,text:'Buongiorno. Piccole cose che rendono la giornata più leggera.',bg:'glass',font:'script',look:'warm',tall:true},
 {id:'s1',cat:'story',title:'Pensiero del giorno',subtitle:'storia',preview:8,photo:true,text:'Le cose semplici hanno ancora molto da dire.',bg:'paper',font:'editorial',look:'soft'},
 {id:'s2',cat:'story',title:'Libro del momento',subtitle:'storia',preview:0,photo:true,text:'Un libro, un caffè e il resto può aspettare.',bg:'dark',font:'serif',look:'cinema',tall:true},
 {id:'q1',cat:'quote',title:'Frase minimal',subtitle:'solo testo',preview:7,photo:false,text:'La mia pace interiore esiste. Ha degli orari molto limitati.',bg:'cream',font:'editorial',look:'original'},
 {id:'q2',cat:'quote',title:'Frase con foto',subtitle:'foto sostituibile',preview:10,photo:true,text:'Stessa vita. Più poesia.',bg:'glass',font:'script',look:'warm'},
 {id:'c1',cat:'carousel',title:'Carosello editoriale',subtitle:'5 slide vuote',preview:5,carousel:true,text:'Titolo del carosello',bg:'dark',font:'editorial',look:'soft',tall:true},
 {id:'c2',cat:'carousel',title:'Liste e consigli',subtitle:'5 slide vuote',preview:7,carousel:true,text:'Una lista da salvare',bg:'cream',font:'serif',look:'warm'},
 {id:'r1',cat:'reel',title:'Reel diario',subtitle:'video da caricare',preview:4,reel:true,text:'Racconta la tua storia',bg:'dark',font:'script',look:'warm'},
 {id:'r2',cat:'reel',title:'Reel minimal',subtitle:'video da caricare',preview:9,reel:true,text:'Un momento da ricordare',bg:'none',font:'editorial',look:'soft'}
];

function normalizePhrase(p){
 const text=(p?.testo??p?.text??'').trim(); if(!text)return null;
 return { ...p, id:p.id||uid('USR'), testo:text, categoria:p.categoria||p.category||'personali', gia_usata:p.gia_usata??p.used??false, attiva_per_suggerimenti:p.attiva_per_suggerimenti??p.active??true };
}
function normalizeSticker(s){ if(!s)return null; return {...s,id:s.id||uid('stk'),category:s.category||s.categoria||'Altro',title:s.title||s.name||'Sticker',file:s.file||s.src}; }
function phraseLabel(cat=''){const m={buongiorno_vita_reale:'Buongiorno · vita reale',buongiorno_maternita:'Buongiorno · maternità',buongiorno_libri:'Buongiorno · libri',maternita:'Maternità',vita_reale:'Vita reale',viaggi:'Viaggi',libri:'Libri',amore_relazioni:'Amore / relazioni',personali:'Personali'};return m[cat]||cat.replaceAll('_',' ')}
function phraseGroup(p){const c=p.categoria||'';if(c.startsWith('buongiorno_'))return 'morning';if(c==='vita_reale')return 'life';if(c==='libri')return 'books';if(c==='maternita')return 'family';if(c==='viaggi')return 'travel';if(c==='amore_relazioni')return 'love';if(c==='personali')return 'personal';return 'other'}

function newSlide(){return{id:uid('slide'),mediaType:null,assetSrc:null,mediaBlob:null,mediaUrl:null,fit:'cover',look:'original',strength:80,bgColor:'#17120f',layers:[]}}
function textLayer(text='Nuova frase',o={}){return{id:uid('txt'),type:'text',text,x:o.x??.5,y:o.y??.62,width:o.width??74,fontSize:o.fontSize??48,font:o.font||'editorial',color:o.color||'#fffaf5',background:o.background||'glass',bgOpacity:o.bgOpacity??76,align:o.align||'center',rotation:o.rotation||0,opacity:o.opacity??100}}
function signatureLayer(){return{id:uid('sig'),type:'signature',x:.5,y:.91,width:48,rotation:0,opacity:100}}
function currentSlide(){return state.slides[state.activeSlide]}
function currentLayer(){return currentSlide()?.layers.find(x=>x.id===state.selectedLayerId)||null}

async function boot(){
 try{
   if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations().catch(()=>[]);for(const r of regs)r.unregister().catch(()=>{});} if('caches'in window){for(const k of await caches.keys().catch(()=>[]))caches.delete(k)}
   const [pr,sr,phr]=await Promise.all([fetch('./photos.json?v=401',{cache:'no-store'}),fetch('./stickers.json?v=401',{cache:'no-store'}),fetch('./phrases.json?v=401',{cache:'no-store'})]);
   photos=await pr.json(); const sd=await sr.json(), pd=await phr.json();
   const builtStickers=(sd.stickers||[]).map(normalizeSticker).filter(x=>x?.file); const builtPhrases=(pd.entries||[]).map(normalizePhrase).filter(Boolean);
   phrases=[...builtPhrases]; stickers=[...builtStickers];
   try{
     await IADB.open();
     const dbP=(await IADB.getAll('phrases')).map(normalizePhrase).filter(Boolean); const pm=new Map(builtPhrases.map(x=>[x.id,x])); dbP.forEach(x=>pm.set(x.id,{...pm.get(x.id),...x})); phrases=[...pm.values()];
     const dbS=(await IADB.getAll('stickers')).map(normalizeSticker).filter(x=>x?.file); const sm=new Map(builtStickers.map(x=>[x.id,x])); dbS.forEach(x=>sm.set(x.id,{...sm.get(x.id),...x})); stickers=[...sm.values()];
     await IADB.bulkPut('phrases',phrases).catch(()=>{}); await IADB.bulkPut('stickers',stickers).catch(()=>{}); projects=await IADB.getAll('projects').catch(()=>[]);
   }catch(e){console.warn('IndexedDB fallback',e);projects=[]}
 }catch(e){console.error('BOOT DATA ERROR',e);toast('Errore nel caricamento dei contenuti')}
 bind(); renderHomePhotos(); renderTemplates(); renderProjects(); renderPhraseBank(); renderStickerBank(); renderLibrary(); renderCounts();
 await sleep(450); $('#boot').classList.add('hidden'); $('#app').classList.remove('hidden'); startHero();
}

function bind(){
 document.addEventListener('click',e=>{
   const nav=e.target.closest('[data-nav]'); if(nav){showScreen(nav.dataset.nav);return}
   const create=e.target.closest('[data-create]'); if(create){startCreation(create.dataset.create);return}
   if(e.target.closest('[data-library-close]'))$('#library-sheet').classList.add('hidden');
 });
 $('#editor-close').onclick=()=>showScreen('home'); $('#editor-save').onclick=saveProject; $('#editor-project').onclick=saveProject; $('#editor-export').onclick=exportCurrent;
 $('#pick-photo').onclick=()=>$('#photo-input').click(); $('#pick-video').onclick=()=>$('#video-input').click(); $('#use-library-photo').onclick=()=>$('#library-sheet').classList.remove('hidden');
 $('#photo-input').onchange=e=>{const f=e.target.files?.[0];if(f)loadLocalMedia(f,'image');e.target.value=''}; $('#video-input').onchange=e=>{const f=e.target.files?.[0];if(f)loadLocalMedia(f,'video');e.target.value=''};
 $('#clear-media').onclick=()=>{const s=currentSlide();revokeSlideUrl(s);s.mediaBlob=null;s.assetSrc=null;s.mediaType=null;renderStage()};
 $('#stage-empty').onclick=()=>selectTool('media'); $('#add-text').onclick=()=>addTextLayer(); $('#new-phrase').onclick=addCustomPhrase; $('#delete-layer').onclick=deleteSelectedLayer; $('#duplicate-layer').onclick=duplicateSelectedLayer;
 $('#text-input').oninput=e=>updateText({text:e.target.value}); $('#text-size').oninput=e=>{updateText({fontSize:+e.target.value});$('#text-size-out').value=e.target.value}; $('#text-width').oninput=e=>{updateText({width:+e.target.value});$('#text-width-out').value=e.target.value+'%'}; $('#text-bg-opacity').oninput=e=>{updateText({bgOpacity:+e.target.value});$('#text-bg-opacity-out').value=e.target.value+'%'}; $('#text-rotation').oninput=e=>{updateText({rotation:+e.target.value});$('#text-rotation-out').value=e.target.value+'°'};
 $('#filter-strength').oninput=e=>{currentSlide().strength=+e.target.value;$('#filter-strength-out').value=e.target.value+'%';renderMediaLook()};
 $('#layer-size').oninput=e=>{const l=currentLayer();if(!l)return;l.width=+e.target.value;$('#layer-size-out').value=e.target.value+'%';renderStage()}; $('#layer-rotation').oninput=e=>{const l=currentLayer();if(!l)return;l.rotation=+e.target.value;$('#layer-rotation-out').value=e.target.value+'°';renderStage()};
 $('#add-signature').onclick=()=>{const s=currentSlide();if(!s.layers.some(x=>x.type==='signature')){const l=signatureLayer();s.layers.push(l);state.selectedLayerId=l.id;renderStage()}}; $('#remove-signature').onclick=()=>{const s=currentSlide();s.layers=s.layers.filter(x=>x.type!=='signature');state.selectedLayerId=null;renderStage()};
 $$('#editor-rail [data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool)); $('#panel-collapse').onclick=()=>$('#editor-panel').classList.toggle('collapsed');
 $$('.editor-subtabs [data-subtab]').forEach(b=>b.onclick=()=>{$$('.editor-subtabs button').forEach(x=>x.classList.toggle('selected',x===b));$$('.subpanel').forEach(x=>x.classList.toggle('active',x.dataset.subpanel===b.dataset.subtab))});
 $$('.fit-row [data-fit]').forEach(b=>b.onclick=()=>{currentSlide().fit=b.dataset.fit;$$('.fit-row [data-fit]').forEach(x=>x.classList.toggle('selected',x===b));renderMediaLook()});
 $('#template-chips').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;$$('#template-chips [data-category]').forEach(x=>x.classList.toggle('selected',x===b));renderTemplates(b.dataset.category)};
 $('#phrase-search').oninput=()=>renderPhraseBank();
}

function startHero(){const arr=$$('.hero-photo');if(arr.length<2)return;setInterval(()=>{arr[heroIndex].classList.remove('active');heroIndex=(heroIndex+1)%arr.length;arr[heroIndex].classList.add('active')},4300)}
function showScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));$('#bottom-dock').classList.toggle('hidden',name==='editor');$$('#bottom-dock [data-nav]').forEach(b=>b.classList.toggle('selected',b.dataset.nav===name));if(name==='templates')renderTemplates();if(name==='projects')renderProjects();if(name==='phrases')renderPhraseBank();if(name==='stickers')renderStickerBank();window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.add('hidden'),2200)}

function renderHomePhotos(){if(!photos.length)return;$('#home-photo-ribbon').innerHTML=photos.map((p,i)=>`<button data-home-photo="${i}"><img src="${p.src}" alt=""></button>`).join('');$$('[data-home-photo]').forEach(b=>b.onclick=()=>startFromLibraryPhoto(+b.dataset.homePhoto))}
function renderLibrary(){if(!photos.length)return;$('#library-grid').innerHTML=photos.map((p,i)=>`<button data-lib-photo="${i}"><img src="${p.src}" alt=""></button>`).join('');$$('[data-lib-photo]').forEach(b=>b.onclick=()=>{const s=currentSlide();revokeSlideUrl(s);s.assetSrc=photos[+b.dataset.libPhoto].src;s.mediaBlob=null;s.mediaType='image';s.look='original';$('#library-sheet').classList.add('hidden');renderStage();toast('Foto inserita')})}
function renderCounts(){$('#phrase-count').textContent=`${phrases.length} frasi`;$('#sticker-count').textContent=`${stickers.length} sticker`}

function renderTemplates(cat='all'){const list=templateDefs.filter(t=>cat==='all'||t.cat===cat);$('#template-grid').innerHTML=list.map(t=>`<button class="template-card ${t.tall?'tall':''}" data-template="${t.id}"><img src="${photos[t.preview]?.src||'./ia_photo_01.webp'}" alt=""><span class="shade"></span><span class="arrow">↗</span><span class="copy"><b>${escapeHtml(t.text)}</b><small>${escapeHtml(t.title)} · ${escapeHtml(t.subtitle)}</small></span></button>`).join('');$$('[data-template]').forEach(b=>b.onclick=()=>useTemplate(b.dataset.template))}
function renderProjects(){const g=$('#project-grid');if(!projects.length){g.innerHTML='<div class="empty-state">Nessun progetto salvato.</div>';return}g.innerHTML=projects.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).map(p=>`<button class="project-card" data-project="${p.id}">${p.thumb?`<img src="${p.thumb}" alt="">`:''}<div><strong>${escapeHtml(p.title||'Progetto')}</strong><small>${escapeHtml(p.kind||'')}</small></div></button>`).join('');$$('[data-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.project))}

function phraseChipData(){return[['all','Tutte'],['morning','Buongiorno'],['life','Vita reale'],['books','Libri'],['family','Maternità'],['travel','Viaggi'],['love','Relazioni'],['personal','Personali']]}
function renderPhraseChips(target,selected,handler){target.innerHTML=phraseChipData().map(([id,n])=>`<button data-pgroup="${id}" class="${id===selected?'selected':''}">${n}</button>`).join('');target.querySelectorAll('[data-pgroup]').forEach(b=>b.onclick=()=>handler(b.dataset.pgroup))}
function filteredPhrases(group='all',query=''){let list=phrases.filter(p=>p.attiva_per_suggerimenti!==false);if(group!=='all')list=list.filter(p=>phraseGroup(p)===group);if(query)list=list.filter(p=>p.testo.toLowerCase().includes(query.toLowerCase()));return list}
function renderPhraseBank(){const q=$('#phrase-search')?.value||'';const chips=$('#phrase-bank-chips');const choose=g=>{chips.dataset.group=g;renderPhraseBank()};const group=chips?.dataset.group||'all';if(chips)renderPhraseChips(chips,group,choose);const list=filteredPhrases(group,q);$('#phrase-bank').innerHTML=list.slice(0,160).map(p=>`<article class="phrase-item"><p>${escapeHtml(p.testo)}</p><small>${escapeHtml(phraseLabel(p.categoria))}</small></article>`).join('')||'<div class="empty-state">Nessuna frase trovata.</div>'}

function stickerCats(){return['Tutti',...new Set(stickers.map(s=>s.category).filter(Boolean))]}
function renderStickerChips(target,selected,handler){target.innerHTML=stickerCats().map(c=>`<button data-scat="${escapeHtml(c)}" class="${c===selected?'selected':''}">${escapeHtml(c)}</button>`).join('');target.querySelectorAll('[data-scat]').forEach(b=>b.onclick=()=>handler(b.dataset.scat))}
function renderStickerBank(){const chips=$('#sticker-bank-chips');const choose=c=>{chips.dataset.cat=c;renderStickerBank()};const cat=chips?.dataset.cat||'Tutti';if(chips)renderStickerChips(chips,cat,choose);const list=stickers.filter(s=>cat==='Tutti'||s.category===cat);$('#sticker-bank').innerHTML=list.map(s=>`<button class="sticker-item"><img src="./${s.file}" alt="${escapeHtml(s.title)}"></button>`).join('')}

function startCreation(kind){state.projectId=null;state.selectedLayerId=null;state.activeSlide=0;state.phraseFilter=kind==='morning'?'morning':'all';state.stickerFilter='Tutti';
 if(kind==='carousel'){state.kind='carousel';state.format='carousel';state.title='Nuovo carosello';state.slides=Array.from({length:5},()=>newSlide());showEditor('media');return}
 state.kind=kind==='reel'?'reel':'story';state.format='story';state.title=kind==='morning'?'Storia del buongiorno':kind==='reel'?'Nuovo reel':'Nuova storia';state.slides=[newSlide()];showEditor(kind==='morning'?'phrases':'media')}
function startFromLibraryPhoto(i){state.kind='story';state.format='story';state.title='Nuova storia';state.projectId=null;state.activeSlide=0;state.selectedLayerId=null;const s=newSlide();s.assetSrc=photos[i].src;s.mediaType='image';state.slides=[s];showEditor('text')}
function useTemplate(id){const t=templateDefs.find(x=>x.id===id);if(!t)return;if(t.carousel){startCreation('carousel');state.slides[0].layers.push(textLayer(t.text,{background:t.bg,font:t.font,y:.65}));state.selectedLayerId=state.slides[0].layers[0].id;renderStage();selectTool('text');return}if(t.reel){startCreation('reel');const l=textLayer(t.text,{background:t.bg,font:t.font,y:.76});currentSlide().layers.push(l);state.selectedLayerId=l.id;renderStage();selectTool('media');return}state.kind='template';state.format='story';state.title=t.title;state.projectId=null;state.activeSlide=0;state.selectedLayerId=null;const s=newSlide();s.look=t.look;s.bgColor=t.photo?'#17120f':'#f3e8df';if(t.photo){s.assetSrc=photos[t.preview]?.src;s.mediaType='image'}const l=textLayer(t.text,{background:t.bg,font:t.font,y:t.photo ? .72 : .5,fontSize:t.photo?48:58,color:t.bg==='cream'||t.bg==='paper'?'#25140d':'#fffaf5'});s.layers=[l];state.slides=[s];state.selectedLayerId=l.id;showEditor('text')}
function showEditor(tool='media'){showScreen('editor');$('#editor-mode-label').textContent=state.kind==='carousel'?'Carosello':state.kind==='reel'?'Reel':state.kind==='template'?'Template':state.title;$('#editor-build').textContent=BUILD;renderStage();renderAllControls();selectTool(tool)}

function revokeSlideUrl(s){if(s?.mediaUrl?.startsWith('blob:')){URL.revokeObjectURL(s.mediaUrl);objectUrls=objectUrls.filter(x=>x!==s.mediaUrl)}if(s)s.mediaUrl=null}
function resolveMediaUrl(s){if(!s)return null;if(s.mediaUrl)return s.mediaUrl;if(s.mediaBlob){s.mediaUrl=URL.createObjectURL(s.mediaBlob);objectUrls.push(s.mediaUrl);return s.mediaUrl}return s.assetSrc||null}
function loadLocalMedia(file,type){const s=currentSlide();if(!s)return;revokeSlideUrl(s);s.mediaBlob=file;s.assetSrc=null;s.mediaType=type;s.mediaUrl=URL.createObjectURL(file);objectUrls.push(s.mediaUrl);s.look='original';renderStage();selectTool(type==='video'?'look':'text');toast(type==='video'?'Video caricato':'Foto caricata')}
function filterCss(s){const t=(s.strength??80)/100;const m={original:[1,1,1,0,0],soft:[1+.07*t,1-.05*t,1-.02*t,.03*t,0],warm:[1+.05*t,1+.08*t,1-.01*t,.16*t,-5*t],cinema:[.98,1-.17*t,1+.10*t,.09*t,-2*t],bw:[1,1-.05*t,1+.08*t,0,0]};const[a,b,c,d,h]=m[s.look]||m.original;return`${s.look==='bw'?`grayscale(${t}) `:''}brightness(${a}) saturate(${b}) contrast(${c}) sepia(${d}) hue-rotate(${h}deg)`}
function renderMediaLook(){const s=currentSlide();for(const el of [$('#stage-image'),$('#stage-video')]){el.style.objectFit=s.fit||'cover';el.style.filter=filterCss(s)}}

function renderStage(){const s=currentSlide();if(!s)return;const stage=$('#media-stage');stage.classList.toggle('format-carousel',state.format==='carousel');stage.classList.toggle('format-story',state.format!=='carousel');$('#stage-bg').style.background=s.bgColor||'#17120f';const img=$('#stage-image'),vid=$('#stage-video'),empty=$('#stage-empty'),url=resolveMediaUrl(s);img.hidden=true;vid.hidden=true;empty.classList.toggle('hidden',!!url);
 if(url&&s.mediaType==='image'){img.hidden=false;if(img.src!==url)img.src=url;img.onerror=()=>toast('Foto non leggibile. Prova JPEG/PNG o una copia dalla Libreria Foto.')}
 if(url&&s.mediaType==='video'){vid.hidden=false;if(vid.src!==url){vid.src=url;vid.load()}vid.onerror=()=>toast('Video non leggibile da Safari. Prova un video della Libreria Foto o MP4/H.264.')}
 renderMediaLook();const root=$('#layer-root');root.innerHTML='';s.layers.forEach(l=>root.appendChild(layerEl(l)));syncTextControls();syncLayerControls();renderCarouselStrip();$('#layer-toolbar').classList.toggle('hidden',!state.selectedLayerId)}
function layerEl(l){const el=document.createElement('div');el.className=`content-layer ${l.type}-layer ${l.type==='text'?`font-${l.font} bg-${l.background}`:''} ${l.id===state.selectedLayerId?'selected':''}`;el.dataset.layerId=l.id;el.style.left=l.x*100+'%';el.style.top=l.y*100+'%';el.style.width=(l.width||40)+'%';el.style.setProperty('--rot',(l.rotation||0)+'deg');el.style.opacity=(l.opacity??100)/100;if(l.type==='text'){el.style.fontSize=(l.fontSize||48)+'px';el.style.color=l.color||'#fff';el.style.textAlign=l.align||'center';el.style.setProperty('--bg-alpha',(l.bgOpacity??76)/100);el.textContent=l.text}else{const im=new Image();im.src=l.type==='signature'?'./signature.svg':l.src;im.alt='';el.appendChild(im)}el.addEventListener('pointerdown',dragLayer);el.onclick=e=>{e.stopPropagation();state.selectedLayerId=l.id;renderStage();selectTool(l.type==='text'?'text':l.type==='sticker'?'stickers':'signature')};return el}
function dragLayer(e){e.preventDefault();const id=e.currentTarget.dataset.layerId,s=currentSlide(),l=s.layers.find(x=>x.id===id),r=$('#media-stage').getBoundingClientRect();if(!l)return;state.selectedLayerId=id;e.currentTarget.setPointerCapture?.(e.pointerId);const mv=ev=>{l.x=clamp((ev.clientX-r.left)/r.width,.03,.97);l.y=clamp((ev.clientY-r.top)/r.height,.03,.97);e.currentTarget.style.left=l.x*100+'%';e.currentTarget.style.top=l.y*100+'%'};const up=()=>{window.removeEventListener('pointermove',mv);renderStage()};window.addEventListener('pointermove',mv);window.addEventListener('pointerup',up,{once:true})}

function renderCarouselStrip(){const st=$('#carousel-strip');if(state.kind!=='carousel'){st.classList.add('hidden');st.innerHTML='';return}st.classList.remove('hidden');st.innerHTML=state.slides.map((s,i)=>{const u=resolveMediaUrl(s);return`<button class="carousel-thumb ${i===state.activeSlide?'selected':''}" data-slide="${i}">${u&&s.mediaType==='image'?`<img src="${u}" alt="">`:`<span class="blank-thumb">${i+1}</span>`}</button>`}).join('')+`<button class="carousel-add" id="carousel-add">+</button>${state.slides.length>1?'<button class="carousel-delete" id="carousel-delete">⌫</button>':''}`;$$('[data-slide]').forEach(b=>b.onclick=()=>{state.activeSlide=+b.dataset.slide;state.selectedLayerId=null;renderStage()});$('#carousel-add').onclick=()=>{if(state.slides.length>=10)return toast('Massimo 10 slide');state.slides.push(newSlide());state.activeSlide=state.slides.length-1;renderStage()};$('#carousel-delete')?.addEventListener('click',()=>{if(state.slides.length<=1)return;const s=state.slides.splice(state.activeSlide,1)[0];revokeSlideUrl(s);state.activeSlide=Math.max(0,state.activeSlide-1);state.selectedLayerId=null;renderStage()})}

function selectTool(tool){state.activeTool=tool;$('#editor-panel').classList.remove('collapsed');$$('#editor-rail [data-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.tool===tool));$$('.tool-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===tool));if(tool==='phrases')renderPhrasePicker();if(tool==='stickers')renderStickerPicker();if(tool==='look')renderLookRow()}
function renderAllControls(){renderFonts();renderBackgrounds();renderColors();renderPhrasePicker();renderStickerPicker();renderLookRow()}
function selectedText(){const l=currentLayer();if(l?.type==='text')return l;return currentSlide()?.layers.find(x=>x.type==='text')||null}
function syncTextControls(){const l=selectedText();$('#text-input').value=l?.text||'';$('#text-size').value=l?.fontSize||48;$('#text-size-out').value=l?.fontSize||48;$('#text-width').value=l?.width||74;$('#text-width-out').value=(l?.width||74)+'%';$('#text-bg-opacity').value=l?.bgOpacity??76;$('#text-bg-opacity-out').value=(l?.bgOpacity??76)+'%';$('#text-rotation').value=l?.rotation||0;$('#text-rotation-out').value=(l?.rotation||0)+'°'}
function syncLayerControls(){const l=currentLayer();if(!l)return;$('#layer-size').value=l.width||30;$('#layer-size-out').value=(l.width||30)+'%';$('#layer-rotation').value=l.rotation||0;$('#layer-rotation-out').value=(l.rotation||0)+'°'}
function updateText(p){const l=selectedText();if(!l)return;Object.assign(l,p);state.selectedLayerId=l.id;renderStage()}
function addTextLayer(text='Nuova frase'){const l=textLayer(text);currentSlide().layers.push(l);state.selectedLayerId=l.id;renderStage();selectTool('text')}
function deleteSelectedLayer(){if(!state.selectedLayerId)return;const s=currentSlide();s.layers=s.layers.filter(x=>x.id!==state.selectedLayerId);state.selectedLayerId=null;renderStage()}
function duplicateSelectedLayer(){const l=currentLayer();if(!l)return;const c={...l,id:uid(l.type),x:clamp(l.x+.06,.05,.95),y:clamp(l.y+.05,.05,.95)};currentSlide().layers.push(c);state.selectedLayerId=c.id;renderStage()}

function renderFonts(){const fonts=[['editorial','Editoriale'],['script','Corsivo'],['serif','Classica'],['rounded','Rotonda'],['modern','Moderna']];$('#font-row').innerHTML=fonts.map(([id,n])=>`<button class="font-option font-${id}" data-font="${id}"><b>Aa</b><small>${n}</small></button>`).join('');$$('[data-font]').forEach(b=>b.onclick=()=>updateText({font:b.dataset.font}))}
function renderBackgrounds(){const a=[['none','Nessuno'],['cream','Avorio'],['dark','Scuro'],['glass','Vetro'],['paper','Carta'],['outline','Linea']];$('#background-row').innerHTML=a.map(([id])=>`<button class="background-option bg-preview-${id}" data-bg="${id}"></button>`).join('');$$('[data-bg]').forEach(b=>b.onclick=()=>updateText({background:b.dataset.bg}))}
function renderColors(){const a=['#fffaf5','#f6f2ea','#e45718','#f3a17f','#2a211d','#0d0d0d','#ffffff'];$('#color-row').innerHTML=a.map(c=>`<button class="color-chip" data-color="${c}" style="background:${c}"></button>`).join('');$$('[data-color]').forEach(b=>b.onclick=()=>updateText({color:b.dataset.color}));$$('[data-align]').forEach(b=>b.onclick=()=>updateText({align:b.dataset.align}))}
function renderLookRow(){const a=[['original','Originale'],['warm','Caldo'],['soft','Soft'],['cinema','Cinema'],['bw','B/N']],s=currentSlide();$('#look-row').innerHTML=a.map(([id,n])=>`<button class="look-option ${s.look===id?'selected':''}" data-look="${id}"><div class="look-thumb" style="filter:${filterCss({...s,look:id})}"></div><b>${n}</b></button>`).join('');$$('[data-look]').forEach(b=>b.onclick=()=>{s.look=b.dataset.look;renderMediaLook();renderLookRow()})}

function renderPhrasePicker(){const chips=$('#phrase-picker-chips');renderPhraseChips(chips,state.phraseFilter,g=>{state.phraseFilter=g;renderPhrasePicker()});const list=filteredPhrases(state.phraseFilter).filter(p=>!p.gia_usata||state.phraseFilter==='personal').slice(0,80);$('#phrase-picker').innerHTML=list.map(p=>`<button class="phrase-pick" data-use-phrase="${p.id}"><p>${escapeHtml(p.testo)}</p><small>${escapeHtml(phraseLabel(p.categoria))}</small></button>`).join('')||'<div class="empty-state">Nessuna frase in questa categoria.</div>';$$('[data-use-phrase]').forEach(b=>b.onclick=()=>{const p=phrases.find(x=>x.id===b.dataset.usePhrase);if(!p)return;const l=selectedText();if(l){l.text=p.testo;state.selectedLayerId=l.id;renderStage();selectTool('text')}else addTextLayer(p.testo)})}
function renderStickerPicker(){const chips=$('#sticker-picker-chips');renderStickerChips(chips,state.stickerFilter,c=>{state.stickerFilter=c;renderStickerPicker()});const list=stickers.filter(s=>state.stickerFilter==='Tutti'||s.category===state.stickerFilter);$('#sticker-picker').innerHTML=list.map(s=>`<button class="sticker-item" data-use-sticker="${s.id}"><img src="./${s.file}" alt="${escapeHtml(s.title)}"></button>`).join('')||'<div class="empty-state">Nessuno sticker.</div>';$$('[data-use-sticker]').forEach(b=>b.onclick=()=>{const s=stickers.find(x=>x.id===b.dataset.useSticker);if(!s)return;const l={id:uid('stk'),type:'sticker',src:'./'+s.file,x:.5,y:.55,width:28,rotation:0,opacity:100};currentSlide().layers.push(l);state.selectedLayerId=l.id;renderStage()})}
async function addCustomPhrase(){const t=prompt('Scrivi la nuova frase');if(!t?.trim())return;const p=normalizePhrase({id:uid('USR'),categoria:'personali',testo:t.trim(),attiva_per_suggerimenti:true,gia_usata:false});phrases.push(p);IADB.put('phrases',p).catch(()=>{});renderPhraseBank();renderCounts();toast('Frase aggiunta')}

async function saveProject(){try{const thumb=await renderComposite(220,state.format==='carousel'?275:390,currentSlide());const rec={id:state.projectId||uid('project'),title:state.title,kind:state.kind,updatedAt:Date.now(),state:serializeState(),thumb:thumb.toDataURL('image/jpeg',.7)};state.projectId=rec.id;await IADB.put('projects',rec);projects=await IADB.getAll('projects');renderProjects();toast('Progetto salvato')}catch(e){console.error(e);toast('Salvataggio non riuscito')}}
function serializeState(){return{kind:state.kind,format:state.format,activeSlide:state.activeSlide,title:state.title,slides:state.slides.map(s=>({...s,mediaUrl:null}))}}
async function openProject(id){const p=projects.find(x=>x.id===id);if(!p)return;state.projectId=p.id;state.kind=p.state.kind;state.format=p.state.format;state.activeSlide=p.state.activeSlide||0;state.title=p.state.title||p.title;state.slides=p.state.slides||[newSlide()];state.selectedLayerId=null;showEditor('media')}

async function exportCurrent(){try{if(state.kind==='reel'&&currentSlide().mediaType==='video')return exportReel();if(state.kind==='carousel')return exportCarousel();const c=await renderComposite(1080,1920,currentSlide()),blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.94));await shareBlob(blob,`IA_story_${dateStamp()}.jpg`,'Ironicamente Acida');markPhraseUsed()}catch(e){console.error(e);toast('Esportazione non riuscita')}}
async function exportCarousel(){const files=[];for(let i=0;i<state.slides.length;i++){const c=await renderComposite(1080,1350,state.slides[i]),b=await new Promise(r=>c.toBlob(r,'image/jpeg',.94));files.push(new File([b],`IA_carosello_${dateStamp()}_${i+1}.jpg`,{type:'image/jpeg'}))}if(navigator.canShare?.({files})&&navigator.share)await navigator.share({files,title:'Ironicamente Acida · Carosello'});else files.forEach(f=>downloadBlob(f,f.name));toast('Carosello pronto')}
async function exportReel(){const s=currentSlide();if(!s.mediaBlob)return toast('Carica prima un video dal telefono');const f=s.mediaBlob instanceof File?s.mediaBlob:new File([s.mediaBlob],`IA_reel_${dateStamp()}.mp4`,{type:s.mediaBlob.type||'video/mp4'});if(navigator.canShare?.({files:[f]})&&navigator.share)await navigator.share({files:[f],title:'Ironicamente Acida · Reel'});else downloadBlob(f,f.name)}
async function shareBlob(blob,name,title){const f=new File([blob],name,{type:blob.type||'image/jpeg'});if(navigator.canShare?.({files:[f]})&&navigator.share)await navigator.share({files:[f],title});else downloadBlob(blob,name)}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}function dateStamp(){return new Date().toISOString().slice(0,10)}
function markPhraseUsed(){const l=currentSlide().layers.find(x=>x.type==='text');if(!l)return;const p=phrases.find(x=>x.testo===l.text);if(p){p.gia_usata=true;p.useCount=(p.useCount||0)+1;IADB.put('phrases',p).catch(()=>{})}}

async function renderComposite(w,h,s){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle=s.bgColor||'#17120f';ctx.fillRect(0,0,w,h);const src=resolveMediaUrl(s);if(src&&s.mediaType==='image'){const im=await loadImage(src);ctx.save();ctx.filter=filterCss(s);drawFit(ctx,im,w,h,s.fit);ctx.restore()}else if(src&&s.mediaType==='video'){const v=$('#stage-video');if(v.readyState>=2){ctx.save();ctx.filter=filterCss(s);drawFit(ctx,v,w,h,s.fit);ctx.restore()}}for(const l of s.layers)await drawLayer(ctx,l,w,h);return c}
function drawFit(ctx,im,w,h,fit='cover'){const iw=im.videoWidth||im.naturalWidth||im.width,ih=im.videoHeight||im.naturalHeight||im.height;if(!iw||!ih)return;const sc=fit==='contain'?Math.min(w/iw,h/ih):Math.max(w/iw,h/ih),dw=iw*sc,dh=ih*sc;ctx.drawImage(im,(w-dw)/2,(h-dh)/2,dw,dh)}
async function drawLayer(ctx,l,w,h){const x=l.x*w,y=l.y*h,bw=(l.width/100)*w;ctx.save();ctx.globalAlpha=(l.opacity??100)/100;ctx.translate(x,y);ctx.rotate((l.rotation||0)*Math.PI/180);if(l.type==='sticker'||l.type==='signature'){const im=await loadImage(l.type==='signature'?'./signature.svg':l.src),ratio=im.naturalHeight/im.naturalWidth;ctx.drawImage(im,-bw/2,-bw*ratio/2,bw,bw*ratio);ctx.restore();return}if(l.type==='text'){const scale=w/360,font=Math.max(18,l.fontSize*scale);ctx.font=fontString(l,font);ctx.textAlign=l.align==='left'?'left':l.align==='right'?'right':'center';ctx.textBaseline='middle';const lines=wrapText(ctx,l.text,bw-32*scale),lh=font*1.08,th=lines.length*lh,pad=18*scale,rh=th+pad*1.45;drawTextBg(ctx,l,-bw/2,-rh/2,bw,rh,18*scale);ctx.fillStyle=l.color||'#fff';const tx=l.align==='left'?-bw/2+pad:l.align==='right'?bw/2-pad:0;lines.forEach((line,i)=>ctx.fillText(line,tx,-(lines.length-1)*lh/2+i*lh))}ctx.restore()}
function fontString(l,s){const m={editorial:`${s}px Didot,Georgia,serif`,script:`${s}px 'Snell Roundhand','Bradley Hand',cursive`,serif:`${s}px Georgia,serif`,rounded:`600 ${s}px 'Avenir Next Rounded','Avenir Next',sans-serif`,modern:`600 ${s}px 'Avenir Next',sans-serif`};return m[l.font]||m.editorial}
function wrapText(ctx,text,max){const out=[];for(const p of String(text||'').split('\n')){let line='';for(const word of p.split(/\s+/)){const t=line?line+' '+word:word;if(ctx.measureText(t).width>max&&line){out.push(line);line=word}else line=t}if(line)out.push(line)}return out.length?out:['']}
function drawTextBg(ctx,l,x,y,w,h,r){const a=(l.bgOpacity??76)/100;if(l.background==='none')return;ctx.save();if(['cream','paper'].includes(l.background))ctx.fillStyle=`rgba(246,242,234,${a})`;else if(l.background==='dark')ctx.fillStyle=`rgba(13,13,13,${a})`;else if(l.background==='glass'){ctx.fillStyle=`rgba(248,232,220,${a*.38})`;ctx.strokeStyle='rgba(255,255,255,.28)';ctx.lineWidth=2}else if(l.background==='outline'){ctx.fillStyle='rgba(0,0,0,.05)';ctx.strokeStyle=`rgba(255,255,255,${Math.max(.45,a)})`;ctx.lineWidth=2}roundRect(ctx,x,y,w,h,l.background==='paper'?r*.45:r);ctx.fill();if(['glass','outline'].includes(l.background))ctx.stroke();ctx.restore()}
function roundRect(ctx,x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function loadImage(src){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=src})}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

boot();
